"""empty message

Revision ID: 8204fae4a9ec
Revises: 
Create Date: 2020-08-28 23:41:02.457642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8204fae4a9ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PictureDate',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Uuid', sa.String(length=64), nullable=True),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Uuid')
    )
    op.drop_table('company')
    op.drop_table('alpaca_training')
    op.drop_table('account')
    op.drop_table('stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('closing_price', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stocks_pkey')
    )
    op.create_table('account',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=355), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='account_pkey'),
    sa.UniqueConstraint('email', name='account_email_key'),
    sa.UniqueConstraint('username', name='account_username_key')
    )
    op.create_table('alpaca_training',
    sa.Column('record_no', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alpaca_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('training', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration', postgresql.INTERVAL(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('record_no', name='alpaca_training_pkey')
    )
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.CHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('salary', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_pkey')
    )
    op.drop_table('PictureDate')
    # ### end Alembic commands ###
